---
- name: Create
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  vars:
    molecule_ephemeral_directory: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
    molecule_scenario_name: "{{ lookup('env', 'MOLECULE_SCENARIO_NAME') }}"
    molecule_project_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    vm_arch: "x86_64"

  tasks:
    - name: Register VMs data
      ansible.builtin.set_fact:
        instance: {
          "instance": "molecule-{{ molecule_project_name }}-{{ molecule_scenario_name }}-{{ item.name }}",
          "name": "{{ item.name }}",
        }
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      register: molecule_instances

    - name: Prepare VMs data
      ansible.builtin.set_fact:
        molecule_instances: "{{ molecule_instances.results | map(attribute='ansible_facts.instance') | list }}"

    - debug: var=molecule_instances

    - name: Register qemu executable path  # noqa: command-instead-of-shell
      ansible.builtin.shell: "command -v qemu-system-{{ vm_arch }}"
      register: qemu_path
      changed_when: false

    - name: Prepare qemu executable path
      ansible.builtin.set_fact:
        qemu_cmd: "{{ qemu_path.stdout }}"

    - debug: var=qemu_cmd
